// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: api/kube_resource/v1/service.proto

package kube_resourcev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BatchUpsertResourceEventsRequest represents a batch of resource events sent by an agent.
type BatchUpsertResourceEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Events        []*KubeResourceEvent   `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchUpsertResourceEventsRequest) Reset() {
	*x = BatchUpsertResourceEventsRequest{}
	mi := &file_api_kube_resource_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertResourceEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertResourceEventsRequest) ProtoMessage() {}

func (x *BatchUpsertResourceEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertResourceEventsRequest.ProtoReflect.Descriptor instead.
func (*BatchUpsertResourceEventsRequest) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *BatchUpsertResourceEventsRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *BatchUpsertResourceEventsRequest) GetEvents() []*KubeResourceEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

// BatchUpsertResourceEventsResponse represents the server's response to a batch upsert.
type BatchUpsertResourceEventsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedCount int32                  `protobuf:"varint,1,opt,name=processed_count,json=processedCount,proto3" json:"processed_count,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BatchUpsertResourceEventsResponse) Reset() {
	*x = BatchUpsertResourceEventsResponse{}
	mi := &file_api_kube_resource_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchUpsertResourceEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchUpsertResourceEventsResponse) ProtoMessage() {}

func (x *BatchUpsertResourceEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchUpsertResourceEventsResponse.ProtoReflect.Descriptor instead.
func (*BatchUpsertResourceEventsResponse) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *BatchUpsertResourceEventsResponse) GetProcessedCount() int32 {
	if x != nil {
		return x.ProcessedCount
	}
	return 0
}

func (x *BatchUpsertResourceEventsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_kube_resource_v1_service_proto protoreflect.FileDescriptor

const file_api_kube_resource_v1_service_proto_rawDesc = "" +
	"\n" +
	"\"api/kube_resource/v1/service.proto\x12\x0ekounner.api.v1\x1a\x1fapi/kube_resource/v1/type.proto\"|\n" +
	" BatchUpsertResourceEventsRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x129\n" +
	"\x06events\x18\x02 \x03(\v2!.kounner.api.v1.KubeResourceEventR\x06events\"f\n" +
	"!BatchUpsertResourceEventsResponse\x12'\n" +
	"\x0fprocessed_count\x18\x01 \x01(\x05R\x0eprocessedCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x98\x01\n" +
	"\x13KubeResourceService\x12\x80\x01\n" +
	"\x19BatchUpsertResourceEvents\x120.kounner.api.v1.BatchUpsertResourceEventsRequest\x1a1.kounner.api.v1.BatchUpsertResourceEventsResponseB@Z>github.com/kimtis/kounner/api/kube_resource/v1;kube_resourcev1b\x06proto3"

var (
	file_api_kube_resource_v1_service_proto_rawDescOnce sync.Once
	file_api_kube_resource_v1_service_proto_rawDescData []byte
)

func file_api_kube_resource_v1_service_proto_rawDescGZIP() []byte {
	file_api_kube_resource_v1_service_proto_rawDescOnce.Do(func() {
		file_api_kube_resource_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kube_resource_v1_service_proto_rawDesc), len(file_api_kube_resource_v1_service_proto_rawDesc)))
	})
	return file_api_kube_resource_v1_service_proto_rawDescData
}

var file_api_kube_resource_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_kube_resource_v1_service_proto_goTypes = []any{
	(*BatchUpsertResourceEventsRequest)(nil),  // 0: kounner.api.v1.BatchUpsertResourceEventsRequest
	(*BatchUpsertResourceEventsResponse)(nil), // 1: kounner.api.v1.BatchUpsertResourceEventsResponse
	(*KubeResourceEvent)(nil),                 // 2: kounner.api.v1.KubeResourceEvent
}
var file_api_kube_resource_v1_service_proto_depIdxs = []int32{
	2, // 0: kounner.api.v1.BatchUpsertResourceEventsRequest.events:type_name -> kounner.api.v1.KubeResourceEvent
	0, // 1: kounner.api.v1.KubeResourceService.BatchUpsertResourceEvents:input_type -> kounner.api.v1.BatchUpsertResourceEventsRequest
	1, // 2: kounner.api.v1.KubeResourceService.BatchUpsertResourceEvents:output_type -> kounner.api.v1.BatchUpsertResourceEventsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_kube_resource_v1_service_proto_init() }
func file_api_kube_resource_v1_service_proto_init() {
	if File_api_kube_resource_v1_service_proto != nil {
		return
	}
	file_api_kube_resource_v1_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kube_resource_v1_service_proto_rawDesc), len(file_api_kube_resource_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_kube_resource_v1_service_proto_goTypes,
		DependencyIndexes: file_api_kube_resource_v1_service_proto_depIdxs,
		MessageInfos:      file_api_kube_resource_v1_service_proto_msgTypes,
	}.Build()
	File_api_kube_resource_v1_service_proto = out.File
	file_api_kube_resource_v1_service_proto_goTypes = nil
	file_api_kube_resource_v1_service_proto_depIdxs = nil
}
