// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: api/kube_resource/v1/service.proto

package kube_resourcev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeResourceService_BatchUpsertResourceEvents_FullMethodName = "/kounner.api.v1.KubeResourceService/BatchUpsertResourceEvents"
)

// KubeResourceServiceClient is the client API for KubeResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KubeResourceService handles resource event collection from agents.
type KubeResourceServiceClient interface {
	// BatchUpsertResourceEvents receives a batch of resource events from an agent.
	BatchUpsertResourceEvents(ctx context.Context, in *BatchUpsertResourceEventsRequest, opts ...grpc.CallOption) (*BatchUpsertResourceEventsResponse, error)
}

type kubeResourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeResourceServiceClient(cc grpc.ClientConnInterface) KubeResourceServiceClient {
	return &kubeResourceServiceClient{cc}
}

func (c *kubeResourceServiceClient) BatchUpsertResourceEvents(ctx context.Context, in *BatchUpsertResourceEventsRequest, opts ...grpc.CallOption) (*BatchUpsertResourceEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertResourceEventsResponse)
	err := c.cc.Invoke(ctx, KubeResourceService_BatchUpsertResourceEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeResourceServiceServer is the server API for KubeResourceService service.
// All implementations must embed UnimplementedKubeResourceServiceServer
// for forward compatibility.
//
// KubeResourceService handles resource event collection from agents.
type KubeResourceServiceServer interface {
	// BatchUpsertResourceEvents receives a batch of resource events from an agent.
	BatchUpsertResourceEvents(context.Context, *BatchUpsertResourceEventsRequest) (*BatchUpsertResourceEventsResponse, error)
	mustEmbedUnimplementedKubeResourceServiceServer()
}

// UnimplementedKubeResourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeResourceServiceServer struct{}

func (UnimplementedKubeResourceServiceServer) BatchUpsertResourceEvents(context.Context, *BatchUpsertResourceEventsRequest) (*BatchUpsertResourceEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchUpsertResourceEvents not implemented")
}
func (UnimplementedKubeResourceServiceServer) mustEmbedUnimplementedKubeResourceServiceServer() {}
func (UnimplementedKubeResourceServiceServer) testEmbeddedByValue()                             {}

// UnsafeKubeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeResourceServiceServer will
// result in compilation errors.
type UnsafeKubeResourceServiceServer interface {
	mustEmbedUnimplementedKubeResourceServiceServer()
}

func RegisterKubeResourceServiceServer(s grpc.ServiceRegistrar, srv KubeResourceServiceServer) {
	// If the following call panics, it indicates UnimplementedKubeResourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeResourceService_ServiceDesc, srv)
}

func _KubeResourceService_BatchUpsertResourceEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertResourceEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeResourceServiceServer).BatchUpsertResourceEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeResourceService_BatchUpsertResourceEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeResourceServiceServer).BatchUpsertResourceEvents(ctx, req.(*BatchUpsertResourceEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeResourceService_ServiceDesc is the grpc.ServiceDesc for KubeResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kounner.api.v1.KubeResourceService",
	HandlerType: (*KubeResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BatchUpsertResourceEvents",
			Handler:    _KubeResourceService_BatchUpsertResourceEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/kube_resource/v1/service.proto",
}
