// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: api/kube_resource/v1/type.proto

package kube_resourcev1

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Operation type for the resource change event
type Operation int32

const (
	Operation_UNKNOWN Operation = 0
	Operation_UPSERT  Operation = 1 // Create or Update
	Operation_DELETE  Operation = 2
)

// Enum value maps for Operation.
var (
	Operation_name = map[int32]string{
		0: "UNKNOWN",
		1: "UPSERT",
		2: "DELETE",
	}
	Operation_value = map[string]int32{
		"UNKNOWN": 0,
		"UPSERT":  1,
		"DELETE":  2,
	}
)

func (x Operation) Enum() *Operation {
	p := new(Operation)
	*p = x
	return p
}

func (x Operation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation) Descriptor() protoreflect.EnumDescriptor {
	return file_api_kube_resource_v1_type_proto_enumTypes[0].Descriptor()
}

func (Operation) Type() protoreflect.EnumType {
	return &file_api_kube_resource_v1_type_proto_enumTypes[0]
}

func (x Operation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation.Descriptor instead.
func (Operation) EnumDescriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_type_proto_rawDescGZIP(), []int{0}
}

// KubernetesResource represents the state of a Kubernetes object
type KubeResource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *KubeResourceID        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                                   // Composite key for identification
	Owner         *KubeResourceOwner     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`                                                                             // Owner information for hierarchical tracking
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Labels for filtering and selection
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                                                           // Reason for events
	CreatedAt     *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamp.Timestamp   `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Payload       []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"` // JSON representation of the Kubernetes object
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeResource) Reset() {
	*x = KubeResource{}
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeResource) ProtoMessage() {}

func (x *KubeResource) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeResource.ProtoReflect.Descriptor instead.
func (*KubeResource) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_type_proto_rawDescGZIP(), []int{0}
}

func (x *KubeResource) GetId() *KubeResourceID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *KubeResource) GetOwner() *KubeResourceOwner {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *KubeResource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubeResource) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *KubeResource) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KubeResource) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *KubeResource) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// ResourceID represents the unique composite key for a resource
type KubeResourceID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	GroupVersion  string                 `protobuf:"bytes,2,opt,name=group_version,json=groupVersion,proto3" json:"group_version,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeResourceID) Reset() {
	*x = KubeResourceID{}
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeResourceID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeResourceID) ProtoMessage() {}

func (x *KubeResourceID) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeResourceID.ProtoReflect.Descriptor instead.
func (*KubeResourceID) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_type_proto_rawDescGZIP(), []int{1}
}

func (x *KubeResourceID) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *KubeResourceID) GetGroupVersion() string {
	if x != nil {
		return x.GroupVersion
	}
	return ""
}

func (x *KubeResourceID) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubeResourceID) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubeResourceID) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ResourceOwner represents the owner of a Kubernetes resource
type KubeResourceOwner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeResourceOwner) Reset() {
	*x = KubeResourceOwner{}
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeResourceOwner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeResourceOwner) ProtoMessage() {}

func (x *KubeResourceOwner) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeResourceOwner.ProtoReflect.Descriptor instead.
func (*KubeResourceOwner) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_type_proto_rawDescGZIP(), []int{2}
}

func (x *KubeResourceOwner) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubeResourceOwner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// ResourceEvent wraps a resource with an operation type
type KubeResourceEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     Operation              `protobuf:"varint,1,opt,name=operation,proto3,enum=kounner.api.v1.Operation" json:"operation,omitempty"`
	Id            *KubeResourceID        `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`             // Target resource ID
	Resource      *KubeResource          `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"` // Full resource state (optional for DELETE)
	Timestamp     *timestamp.Timestamp   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubeResourceEvent) Reset() {
	*x = KubeResourceEvent{}
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubeResourceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubeResourceEvent) ProtoMessage() {}

func (x *KubeResourceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_kube_resource_v1_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubeResourceEvent.ProtoReflect.Descriptor instead.
func (*KubeResourceEvent) Descriptor() ([]byte, []int) {
	return file_api_kube_resource_v1_type_proto_rawDescGZIP(), []int{3}
}

func (x *KubeResourceEvent) GetOperation() Operation {
	if x != nil {
		return x.Operation
	}
	return Operation_UNKNOWN
}

func (x *KubeResourceEvent) GetId() *KubeResourceID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *KubeResourceEvent) GetResource() *KubeResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *KubeResourceEvent) GetTimestamp() *timestamp.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_api_kube_resource_v1_type_proto protoreflect.FileDescriptor

const file_api_kube_resource_v1_type_proto_rawDesc = "" +
	"\n" +
	"\x1fapi/kube_resource/v1/type.proto\x12\x0ekounner.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n" +
	"\fKubeResource\x12.\n" +
	"\x02id\x18\x01 \x01(\v2\x1e.kounner.api.v1.KubeResourceIDR\x02id\x127\n" +
	"\x05owner\x18\x02 \x01(\v2!.kounner.api.v1.KubeResourceOwnerR\x05owner\x12@\n" +
	"\x06labels\x18\x03 \x03(\v2(.kounner.api.v1.KubeResource.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x01\n" +
	"\x0eKubeResourceID\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12#\n" +
	"\rgroup_version\x18\x02 \x01(\tR\fgroupVersion\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\";\n" +
	"\x11KubeResourceOwner\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xf0\x01\n" +
	"\x11KubeResourceEvent\x127\n" +
	"\toperation\x18\x01 \x01(\x0e2\x19.kounner.api.v1.OperationR\toperation\x12.\n" +
	"\x02id\x18\x02 \x01(\v2\x1e.kounner.api.v1.KubeResourceIDR\x02id\x128\n" +
	"\bresource\x18\x03 \x01(\v2\x1c.kounner.api.v1.KubeResourceR\bresource\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp*0\n" +
	"\tOperation\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02B@Z>github.com/kimtis/kounner/api/kube_resource/v1;kube_resourcev1b\x06proto3"

var (
	file_api_kube_resource_v1_type_proto_rawDescOnce sync.Once
	file_api_kube_resource_v1_type_proto_rawDescData []byte
)

func file_api_kube_resource_v1_type_proto_rawDescGZIP() []byte {
	file_api_kube_resource_v1_type_proto_rawDescOnce.Do(func() {
		file_api_kube_resource_v1_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_kube_resource_v1_type_proto_rawDesc), len(file_api_kube_resource_v1_type_proto_rawDesc)))
	})
	return file_api_kube_resource_v1_type_proto_rawDescData
}

var file_api_kube_resource_v1_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_kube_resource_v1_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_kube_resource_v1_type_proto_goTypes = []any{
	(Operation)(0),              // 0: kounner.api.v1.Operation
	(*KubeResource)(nil),        // 1: kounner.api.v1.KubeResource
	(*KubeResourceID)(nil),      // 2: kounner.api.v1.KubeResourceID
	(*KubeResourceOwner)(nil),   // 3: kounner.api.v1.KubeResourceOwner
	(*KubeResourceEvent)(nil),   // 4: kounner.api.v1.KubeResourceEvent
	nil,                         // 5: kounner.api.v1.KubeResource.LabelsEntry
	(*timestamp.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_api_kube_resource_v1_type_proto_depIdxs = []int32{
	2, // 0: kounner.api.v1.KubeResource.id:type_name -> kounner.api.v1.KubeResourceID
	3, // 1: kounner.api.v1.KubeResource.owner:type_name -> kounner.api.v1.KubeResourceOwner
	5, // 2: kounner.api.v1.KubeResource.labels:type_name -> kounner.api.v1.KubeResource.LabelsEntry
	6, // 3: kounner.api.v1.KubeResource.created_at:type_name -> google.protobuf.Timestamp
	6, // 4: kounner.api.v1.KubeResource.updated_at:type_name -> google.protobuf.Timestamp
	0, // 5: kounner.api.v1.KubeResourceEvent.operation:type_name -> kounner.api.v1.Operation
	2, // 6: kounner.api.v1.KubeResourceEvent.id:type_name -> kounner.api.v1.KubeResourceID
	1, // 7: kounner.api.v1.KubeResourceEvent.resource:type_name -> kounner.api.v1.KubeResource
	6, // 8: kounner.api.v1.KubeResourceEvent.timestamp:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_kube_resource_v1_type_proto_init() }
func file_api_kube_resource_v1_type_proto_init() {
	if File_api_kube_resource_v1_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_kube_resource_v1_type_proto_rawDesc), len(file_api_kube_resource_v1_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_kube_resource_v1_type_proto_goTypes,
		DependencyIndexes: file_api_kube_resource_v1_type_proto_depIdxs,
		EnumInfos:         file_api_kube_resource_v1_type_proto_enumTypes,
		MessageInfos:      file_api_kube_resource_v1_type_proto_msgTypes,
	}.Build()
	File_api_kube_resource_v1_type_proto = out.File
	file_api_kube_resource_v1_type_proto_goTypes = nil
	file_api_kube_resource_v1_type_proto_depIdxs = nil
}
